<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>The communal .NET library for the CompatibleAI service API.</Description>
    <AssemblyTitle>CompatibleAI client library for .NET</AssemblyTitle>

    <TargetFrameworks>$(ClientTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(RepositoryRoot)eng\CompatibleAI.png" Pack="true" PackagePath="\" />
    <None Include="$(RepositoryRoot)CHANGELOG.md" Pack="true" PackagePath="\" />
    <None Include="$(RepositoryRoot)README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\OpenAI.Responses\src\Custom\**\*.cs" LinkBase="Responses\Custom" />
    <Compile Include="..\..\OpenAI.Responses\src\Generated\**\*.cs" LinkBase="Responses\Generated" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ClientModel" />
    <PackageReference Include="System.Net.ServerSentEvents" />
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">
    <PackageReference Include="System.Diagnostics.DiagnosticSource" />
  </ItemGroup>
</Project>
